### ISSUE TITLE
Top-level filtering of one-to-many embedded resources with is.null and not.is.null silently malfunctions

### ISSUE THREAD

**Issue by zachblume** [PostgREST/postgrest#2965]
### Environment

* PostgreSQL version: supabase/postgres:15.1.0.90
* PostgREST version: postgrest:latest (sha256:4fc9e48855f8cf192f067fcc1c5b5d7ce791e8ab3755737f13691c82eeb18f65)
* Operating system: OSX 13.5.2 (22G91)

### Description of issue

(Expected behavior vs actual behavior)
Top-level filtering silently produces incorrect results unless you use spread operator on tables with one-to-many relationship going one direction

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)
```
-- Create the people table
CREATE TABLE people (
    person_id SERIAL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL
);

-- Create the interactions table
CREATE TABLE interactions (
    interaction_id SERIAL PRIMARY KEY,
    person_id INT REFERENCES people(person_id), -- Foreign Key referencing the people table
    notes TEXT
);

-- Inserting example data into the people table
INSERT INTO people (first_name, last_name) VALUES ('John', 'Doe');
INSERT INTO people (first_name, last_name) VALUES ('Jane', 'Smith');
INSERT INTO people (first_name, last_name) VALUES ('Alice', 'Johnson');
INSERT INTO people (first_name, last_name) VALUES ('Bob', 'Williams');
INSERT INTO people (first_name, last_name) VALUES ('Charlie', 'Brown');

-- Inserting example data into the interactions table
INSERT INTO interactions (person_id, notes) VALUES (1, 'Met at a conference.');
INSERT INTO interactions (person_id, notes) VALUES (2, 'Had a phone call regarding the project.');
INSERT INTO interactions (person_id, notes) VALUES (3, 'Sent an email about the upcoming meeting.');
INSERT INTO interactions (person_id, notes) VALUES (4, 'Discussed the new proposal.');
INSERT INTO interactions (person_id, notes) VALUES (5, 'Met for coffee to discuss collaboration.');
```

`http://localhost:8000/rest/v1/interactions?select=*,people(*)&people.or=(first_name.ilike.%John%)&or=(people.not.is.null)`
no results

add the spread operator before people:
`http://localhost:8000/rest/v1/interactions?select=*,...people(first_name)&people.or=(first_name.ilike.%John%)`
and you get the right results

**Comment by zachblume** [comment]
More minimal:
`http://localhost:8000/rest/v1/interactions?select=*,people(*)&people=not.is.null` produces no result even though there are interactions with an associated person

**Comment by laurenceisla** [comment]
> `http://localhost:8000/rest/v1/interactions?select=*,people(*)&people.or=(first_name.ilike.%John%)&or=(people.not.is.null)` no results

By "no results", do you mean that you get an empty array `[]`? Because for me, it returns a single value: the one that has "John" in its first_name.

> More minimal: `http://localhost:8000/rest/v1/interactions?select=*,people(*)&people=not.is.null` produces no result even though there are interactions with an associated person

This also filter correctly all the interactions that have people in it. Perhaps it has something to do with Row Level Security on the tables or something similar? I also tested it on a supabase instance as yourself  and it gave the same correct results.

If you're also testing locally, those `/rest/v1/` should not be included in the query, they give empty results otherwise (just to try possibilities).

**Comment by zachblume** [comment]
Hm, I may be describing this inaccurately or writing down an minimal version slightly wrong. Thanks for checking it so quickly, I was going down a ugly different route towards fixing this in production so I'm glad it could be a simpler error. I'm reproducing with Supabase and I don't think it's RLS unless there's an RLS-specific bug here. Let me reproduce it myself in the most minimal way and follow up.

**Comment by zachblume** [comment]
OK, I reproduced that the minimal examples actually does work correctly in a minimal setup - https://github.com/zachblume/postgrest-bug-reproduction-docker

^that might be a helpful repo for people to fork when they want to show issues

Going to work on isolating this a bit better because there's some shape to it happening in my production environment...

**Comment by zachblume** [comment]
Wow, we love spelling errors

Typo in column names in prod.

Closing this, thank you for your help again @laurenceisla and the great work you all have done on resource embedding.

**Comment by zachblume** [comment]
I spoke too soon.

```
git clone -b error-showing-now https://github.com/zachblume/postgrest-bug-reproduction-docker.git
cd postgrest-bug-reproduction-docker
make
```

Test will fail and show that the output of the fetch is empty!

To see the DDL changes I made to make this fail, here's a diff:
https://github.com/zachblume/postgrest-bug-reproduction-docker/pull/1

**Comment by laurenceisla** [comment]
Ah, I see the problem now. This looks like the same issue as #2800, which was fixed in this commit: https://github.com/PostgREST/postgrest/commit/fa182c216eb412469d8cad15cc9a112156522b91

If you change `postgrest:v11.2.0` to `postgrest:latest`, you should see a result now, because `latest` has that fix in it.

**Comment by zachblume** [comment]
Oh interesting. But: I just updated that reproduction branch to `postgrest:latest` and it still fails!

**Comment by zachblume** [comment]
Removing `batch_id` fixes things though.

**Comment by laurenceisla** [comment]
> Oh interesting. But: I just updated that reproduction branch to `postgrest:latest` and it still fails!

True that, I forgot that the docker image uses the latest stable release. A workaround would be to explicitly remove `batch_id` from the `select=people(...)` query for now, until the new release includes this fix.

**Comment by zachblume** [comment]
Would it need to be: remove any nullable fields?

I actually already patched it prod with the horrible workaround of a overriding computed relationship giving back an array of rows since it's only one-to relationships that display this behavior, but I might patch again with the nullable fix if thats it!

**Comment by laurenceisla** [comment]
> Would it need to be: remove any nullable fields?

Well, yes, the bug triggers when there are nullable fields in a `to-one` relationship.

**Comment by zachblume** [comment]
Okay, that's a little hard to manage in prod so I'll keep my hacky fix until this is deployed in Supabase! Thank you.

**Comment by steve-chavez** [comment]
@laurenceisla Should we consider this a duplicate of #2800?

**Comment by laurenceisla** [comment]
> @laurenceisla Should we consider this a duplicate of #2800?

Yes, it's the same issue, so I'll close it right now. The latest binary has the fix, although Docker needs the next version release to include it.
